apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: graylog

secretGenerator:
  - name: graylog-certs
    files:
      - certs/root-ca.pem

configMapGenerator:
  - name: conf-files
    files:
      - config/graylog-init-content-pack.json
      - config/graylog.conf
      - config/log4j2.xml

resources:
  - graylog-ns.yaml

  - secrets/graylog-cred-secret.yaml
  - secrets/mongo-db-cred-secret.yaml
  - secrets/elastic-cred-secret.yaml

  - graylog-svc.yaml
  - graylog-sts.yaml
  - graylog-inputs-svc.yaml
