apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: datastore
  labels:
    app: wazuh-indexer
spec:
  selector:
    app: wazuh-indexer
  ports:
    - name: indexer-nodes
      port: 9300
      targetPort: 9300
    - name: indexer-rest
      port: 9200
      targetPort: 9200
  clusterIP: None
