apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datastore

resources:
  - datastore-ns.yaml

  - secrets/mariadb-cred-secret.yaml
  
  - mariadb/mariadb-svc.yaml
  - mariadb/mariadb-sts.yaml

  - redis/redis-svc.yaml
  - redis/redis-sts.yaml