apiVersion: v1
kind: Service
metadata:
  name: shuffle-frontend
  namespace: shuffle
  labels:
    app: shuffle-frontend
spec:
  type: LoadBalancer
  selector:
    app: shuffle-frontend
  ports:
    - name: sh-front-https
      port: 443
      targetPort: 443
    - name: sh-front-http
      port: 80
      targetPort: 80
