apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      volumes:
        - name: mongo-config
          configMap:
            name: conf-files
      containers:
        - name: mongo
          image: mongo:5.0.13
          volumeMounts:
            - name: mongo
              mountPath: /data/db
            - name: mongo-config
              mountPath: /docker-entrypoint-initdb.d/mongo-init.sh
              subPath: mongo-init.sh
              readOnly: true
          ports:
            - containerPort: 27017
              name: mongo-port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: root_password
            - name: MONGO_GRAYLOG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: mongo
        namespace: datastore
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: app-storage
        resources:
          requests:
            storage: 5Gi
