apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  user: YWRtaW4=            # admin
  password: YWRtaW4=        # admin
  admin: YWRtaW4=           # admin
  admin_password: YWRtaW4=  # admin
  database: aXJpc19kYg==    # iris_db
  port: NTQzMg==            # 5432
