# Configuration file version
apiVersion: 1

datasources:
  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: https://wazuh-indexer.datastore.svc.cluster.local:9200
    basicAuth: true
    basicAuthUser: grafana
    isDefault: true
    jsonData:
      flavor: "opensearch"
      database: "*"
      version: "2.6.0"
      pplEnabled: false
      timeField: "timestamp"
      tlsAuth: false
      tlsSkipVerify: true
      tlsAuthWithCACert: false
      logMessageField: rule_description
      logLevelField: syslog_level
      dataLinks:
        - field: ^data_vulnerability_cve$
          url: 'https://nvd.nist.gov/vuln/detail/$${__value.raw}' # Careful about the double "$$" because of env var expansion
        - field: ^_id$
          url: 'https://localhost:8443/explore?left=%5B%22now-6h%22,%22now%22,%22OpenSearch%22,%7B%22refId%22:%22A%22,%22query%22:%22_id:$${__value.raw}%22,%22alias%22:%22%22,%22metrics%22:%5B%7B%22id%22:%221%22,%22type%22:%22logs%22,%22settings%22:%7B%22limit%22:%22500%22%7D%7D%5D,%22bucketAggs%22:%5B%5D,%22timeField%22:%22timestamp%22%7D%5D' # Careful about the double "$$" because of env var expansion
    secureJsonData:
      basicAuthPassword: "SecretPassword"
    version: 1
    editable: true