apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velociraptor

configMapGenerator:
  - name: conf-files
    files:
      - config/start.sh

resources:
  - velociraptor-ns.yaml

  - secrets/velociraptor-cred-secret.yaml

  - velociraptor-sts.yaml
  - velociraptor-svc.yaml


