apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iris
  name: iris-rabbitmq-deployment
  labels:
    app: iris-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-rabbitmq
  template:
    metadata:
      labels:
        app: iris-rabbitmq
    spec:
      containers:
      - name: iris-rabbitmq
        image: rabbitmq:3-management-alpine
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 750Mi
        ports:
        - containerPort: 5672