apiVersion: v1
kind: Service
metadata:
  name: elastalert
  namespace: elastalert
  labels:
    app: elastalert
spec:
  selector:
    app: elastalert
  ports:
    - port: 3030
      targetPort: 3030
      name: el-port-1
    - port: 3333
      targetPort: 3333
      name: el-port-2
  clusterIP: None
