
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: datastore
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
