apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datastore

configMapGenerator:
  - name: conf-files
    files:
      - config/postgres-init.sh

resources:
  - datastore-ns.yaml
  
  - secrets/postgres-cred-secret.yaml

  - postgres/postgres-svc.yaml
  - postgres/postgres-sts.yaml