apiVersion: v1
kind: Service
metadata:
  name: iris-rabbitmq
  namespace: iris
  labels:
    app: iris-rabbitmq
spec:
  selector:
    app: iris-rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
  clusterIP: None
