apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shuffle

resources:
  - shuffle-ns.yaml

  - shuffle-role.yaml

  - backend/backend-sts.yaml
  - backend/backend-svc.yaml

  - frontend/frontend-deploy.yaml
  - frontend/frontend-svc.yaml

  - orborus/orborus-deploy.yaml