apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: misp

resources:
  - storage-class.yaml

  - misp-ns.yaml

  - secrets/mariadb-cred-secret.yaml
  - secrets/misp-secret.yaml

  - misp-sts.yaml
  - misp-svc.yaml

  - misp-modules-sts.yaml
  - misp-modules-svc.yaml


