apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffle-orborus
  namespace: shuffle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shuffle-orborus
  template:
    metadata:
      labels:
        app: shuffle-orborus
      name: shuffle-orborus
    spec:
      containers:
        - name: shuffle-orborus
          image: 'ghcr.io/shuffle/shuffle-orborus:1.3.1'
          resources:
            limits:
              cpu: 900m
              memory: 3Gi
          env:
            - name: BASE_URL
              value: "http://shuffle-backend.shuffle.svc.cluster.local:5001"
            - name: SHUFFLE_APP_SDK_VERSION
              value: "1.3.1"
            - name: SHUFFLE_SCALE_REPLICAS
              value: "5"
            - name: SHUFFLE_WORKER_VERSION
              value: "1.3.1"
            - name: IS_KUBERNETES
              value: "true"
            - name: SHUFFLE_KUBERNETES_WORKER
              value: "ghcr.io/shuffle/shuffle-worker:1.3.1"