apiVersion: v1
kind: Service
metadata:
  name: shuffle-backend
  namespace: shuffle
  labels:
    app: shuffle-backend
spec:
  type: LoadBalancer
  selector:
    app: shuffle-backend
  ports:
    - name: sh-back-port
      port: 5001
      targetPort: 5001
