apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: grafana
  labels:
    app: grafana-dashboard
spec:
  type: LoadBalancer
  selector:
    app: grafana-dashboard
  ports:
    - name: dashboard
      port: 443
      targetPort: http-grafana
