# Custom Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false
output.logstash:
  hosts: ["graylog-inputs.graylog.svc.cluster.local:5044"]

logging.metrics.enabled: false
seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
    - rseq