apiVersion: v1
kind: Service
metadata:
  name: misp
  namespace: misp
  labels:
    app: misp
spec:
  selector:
    app: misp
  ports:
    - port: 80
      targetPort: 80
      name: misp-port-http
    - port: 50000
      targetPort: 50000
      name: misp-z-port
  clusterIP: None
