apiVersion: v1
kind: Service
metadata:
  name: iris-app
  namespace: iris
  labels:
    app: iris-app
spec:
  selector:
    app: iris-app
  ports:
    - port: 8000
      targetPort: 8000
  clusterIP: None
